doorsale/payments/urls.py
from django.conf.urls import url

from doorsale.payments.views import process_online, process_credit_card, \
    process_account_request, process_account_response, ProcessingMessageView

urlpatterns = [
    url(r'^process_online/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_online, name='payments_process_online'),
    url(r'^process_credit_card/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_credit_card, name='payments_process_credit_card'),
    url(r'^process_account/request/(?P<order_id>\d+)-(?P<receipt_code>\w+)/$',
        process_account_request, name='payments_process_account_request'),
    url(r'^process_account/success/(?P<transaction_id>\d+)-(?P<access_token>\w+)/$',
        process_account_response, {'success': True}, name='payments_process_account_success'),
    url(r'^process_account/cancel/(?P<transaction_id>\d+)-(?P<access_token>\w+)/$',
        process_account_response, {'success': False}, name='payments_process_account_cancel'),
    url(r'^processing_message/$', ProcessingMessageView.as_view(),
        name='payments_processing_message'),
]

doorsale/payments/forms.py
import re
import datetime

from django import forms

from doorsale.payments.models import Gateway


class CreditCardForm(forms.Form):
    """
    Credit card payment form
    """
    REGEX_EXPIRY = re.compile(r'^(\d{2})\s/\s(\d{2})$')
    REGEX_CVV2 = re.compile(r'^(\d{3,4})$')

    gateway = forms.ModelChoiceField(queryset=Gateway.objects.filter(is_active=True, accept_credit_card=True),
                                     empty_label=None, widget=forms.HiddenInput())
    card_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Name...'}),
                                error_messages={'required': 'Please specify name on credit card.'})
    card_number = forms.CharField(max_length=24, widget=forms.TextInput(attrs={'placeholder': 'Number...'}),
                                  error_messages={'required': 'Please specify credit card number.'})
    card_type = forms.CharField(widget=forms.HiddenInput(), required=False)
    expire_date = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'placeholder': 'MM / YY'}),
                                  error_messages={'required': 'Please specify card expiry date'})
    cvv2 = forms.CharField(max_length=4, widget=forms.TextInput(attrs={'placeholder': 'CVV2...'}),
                           error_messages={'required': 'Please specify card security code'})

    def clean_card_number(self):
        card_number = self.cleaned_data['card_number'].replace(' ', '')
        try:
            int(card_number)
        except ValueError:
            raise forms.ValidationError("Please specify correct card number.")

        return card_number

    def clean_card_type(self):
        card_type = self.cleaned_data.get('card_type', None)
        card_number = self.cleaned_data.get('card_number', None)

        if card_number and not card_type:
            raise forms.ValidationError('We can\'t recognize your card issuer type.')

        return card_type

    def clean_expire_date(self):
        expire_date = self.cleaned_data['expire_date']
        match = self.REGEX_EXPIRY.search(expire_date)

        if match:
            month, year = match.groups()
            try:
                expire_date = datetime.date(2000 + int(year), int(month), 1)
                if expire_date > datetime.date.today():
                    return expire_date
                else:
                    raise forms.ValidationError("Card expiry date has already been passed.")
            except ValueError:
                pass

        raise forms.ValidationError("Please specify correct card expiry date.")

    def clean_cvv2(self):
        cvv2 = self.cleaned_data['cvv2']

        if not self.REGEX_CVV2.search(cvv2):
            raise forms.ValidationError("Please specify correct card security code.")

        return cvv2

    def clean(self):
        cleaned_data = super(CreditCardForm, self).clean()

        if ('card_name' in cleaned_data and 'card_number' in cleaned_data and
                'card_type' in cleaned_data and 'expire_date' in cleaned_data and 'cvv2' in cleaned_data):

            card_name = cleaned_data['card_name']
            expire_date = cleaned_data['expire_date']

            cleaned_data['card'] = {
                'number': cleaned_data['card_number'],
                'type': cleaned_data['card_type'],
                'cvv2': cleaned_data['cvv2'],
                'name': card_name,
                'first_name': card_name.split(' ')[0],
                'last_name': ' '.join(card_name.split(' ')[1:]),
                'expire_month': str(expire_date.month),
                'expire_year': str(expire_date.year)
            }

        return cleaned_data

doorsale/payments/templates/payments/credit_card_processed.html
<div class="credit-card-processed">
    <p class="info-message-box">
        <i class="fa fa-credit-card"></i>
        Your credit card has been processed successfully. redirecting<span id="dots" class="text"></span>
    </p>
    <p>
        <br/>   
        <a id="a-order-receipt" href="{% url 'sales_checkout_receipt' order.id order.receipt_code %}" style="display: none;">View your order receipt here...</a>
    </p>
</div>
<script type="text/javascript">
    setTimeout(function(){
        $('#a-order-receipt').fadeIn(1000);
        window.location = $('#a-order-receipt').attr('href');
    }, 3000);

    setInterval(aniDots, 600);
    function aniDots() {
        if(dots < 3) {
            $('#dots').append('.');
            dots++;
        } else {
            $('#dots').html('');
            dots = 0;
        }
    }
</script>

doorsale/payments/templates/payments/process_online.html
{% load catalog_filters %}

<div id="payment-options">
    <ul>
        {% if form %}
        <li><a href="#payment-credit-card">Credit Card</a></li>
        {% endif %}
        {% for gateway in gateways %}
        {% if gateway.accept_account %}
        <li><a href="#payment-{{ gateway.get_name_display }}">{{ gateway.get_name_display }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
    {% if form %}
    <div id="payment-credit-card" class="credit-card action-form">
        <form method="post" data-ajax="true" action="{% url 'payments_process_credit_card' order.id order.receipt_code %}" data-ajax-update="#payment-options-container" data-ajax-loading="#process-credit-card">
            {% csrf_token %}
            {{ form.gateway }}
            <ul>
                {% if error %}
                <li class="error-message-box">
                    {{ error }}
                </li>
                {% endif %}
                <li>
                    <i class="fa fa-user"></i>
                    {{ form.card_name }}
                    {{ form.card_name.errors }}
                </li>
                <li>
                    <i class="fa fa-credit-card"></i>
                    {{ form.card_number }}
                    <i class="fa fa-check"></i>
                    {{ form.card_number.errors }}
                    {{ form.card_type.errors }}
                </li>
                <li class="dual-input">
                    <span>
                        <i class="fa fa-calendar-o"></i>
                        {{ form.expire_date }}
                    </span>
                    <span>
                        <i class="fa fa-lock fa-lg"></i>
                        {{ form.cvv2 }}
                    </span>
                    <br/>
                    {{ form.expire_date.errors }}
                    {{ form.cvv2.errors }}
                </li>
                <li class="pay-botton-container">
                    <i id="process-credit-card" class="fa fa-spinner fa-lg fa-spin"></i>
                    <input type="submit" value="Pay {{ order.total|currency:default_currency }}" class="pay-button" onclick="javascript:$(this).attr('disabled','disabled');" />
                </li>
            </ul>
            {{ form.card_type }}
        </form>
    </div>
    {% endif %}
    {% for gateway in gateways %}
    {% if gateway.accept_account %}
    <div id="payment-{{ gateway.get_name_display }}" class="action-form online-account" >
        <form method="post" action="{% url 'payments_process_account_request' order.id order.receipt_code %}">
            {% csrf_token %}
            <input type="hidden" name="gateway_name" value="{{ gateway.name }}"/>
            <ul>
                <li class="info-message-box">
                    Check out with your existing {{ gateway.get_name_display }} account.
                </li>
                <li class="pay-botton-container">
                   <input type="submit" value="Pay {{ order.total|currency:default_currency }}" class="pay-button" />
                </li>
            </ul>
        </form>
    </div>
    {% endif %}
    {% endfor %}
</div>
<script type="text/javascript">
    // Detect Credit Card Type by Card Number and
    // fills appropiate type automatically in Card Type
    var $cardNumber = $('#id_card_number')
    $cardNumber.change(function(){
        $cardNumber.validateCreditCard(function(result){
            $('#id_card_type').val('');
            $('#payment-options .action-form .fa-check').hide();

            // Removed error highlight if user corrected his card number
            if($cardNumber.hasClass('input-error') && result.length_valid && result.luhn_valid)
                $cardNumber.removeClass('input-error');

            if(result.card_type) {
                $('#id_card_type').val(result.card_type.name);
                $('#payment-options .action-form .fa-check').css('display', 'inline-block');

                // Highlight card number if wrong when user done with entering
                if(!$cardNumber.is(':focus') && (!result.length_valid || !result.luhn_valid))
                    $cardNumber.addClass('input-error');
            }
        });
    });

    // Payments options in tabs
    $('#payment-options').tabs();

    // Initializing new forms in payment options for ajax requests
    bootstrapAjax($, '#payment-options');

    // Masking inforce correct inputs
    $.mask.definitions['0']='[01]';

    $('#id_card_number').mask('9999 9999 9999 9999? 9999', {placeholder: ' '});
    $('#id_expire_date').mask('09 / 99', {placeholder: '_'});
    $('#id_cvv2').mask('999?9', {placeholder: ' '});
</script>

doorsale/payments/templates/payments/processing_message.html
{% extends catalog_template_name %}

{% block catalog-content %}
<div>
    <h3>Payment Transaction</h3>
    {% if error %}
    <div class="error-message-box">
        {{ error }}
    </div>
    {% else %}
    <div class="info-message-box">
        {{ message }}
    </div>
    {% endif %}
</div>   
{% endblock %}